@SimpleAPI_HostAddress = https://localhost:7025

// Register Item
POST {{SimpleAPI_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"feed the cat",
  "isComplete":false
}

###

// Get Items
GET {{SimpleAPI_HostAddress}}/todoitems

###

// Get Item by Id
GET {{SimpleAPI_HostAddress}}/todoitems/2

###

// Update Item by Id
PUT {{SimpleAPI_HostAddress}}/todoitems/1
Content-Type: application/json

{
   "name":"wash the dishes",
  "isComplete":true
}

###

// Delete Item
DELETE {{SimpleAPI_HostAddress}}/todoitems/4

###

// Get Completed (true) Items
GET {{SimpleAPI_HostAddress}}/todoitems/complete

###
